translated generics channel
GolangUA/ardanlabs-gotour pull request #4
Opened 2024-06-08 18:59 UTC by hrvadl

2024-06-09 08:18 UTC, bulaiocht requested changes
Трошки треба поправити

2024-06-09 08:18 UTC, girthybean commented on _content/tour/ukr/generics-channels.article
> +узагальненим типом Result. Цей канал повертається до того, хто викликав, щоб
```suggestion
узагальненим типом Result. Цей канал повертається тому, хто викликав функцію, щоб
```

2024-06-09 08:18 UTC, girthybean commented on _content/tour/ukr/generics-channels.article
> +виконати фукнцію-робітника конкуретно. Коли функція-робітник завершує виконання, значення,
```suggestion
виконати фукнцію-робітник конкуретно. Коли функція-робітник завершує виконання, значення,
```

2024-06-09 08:18 UTC, girthybean commented on _content/tour/ukr/generics-channels.article
> +Компілятор спроможній визначити конкретнй тип, який використовується для узагальненого типа
```suggestion
Компілятор спроможний визначити конкретнй тип, який використовується для узагальненого типа
```

2024-06-09 08:18 UTC, girthybean commented on _content/tour/ukr/generics-channels.article
> +doWork. Це чудово, тому що це значить, що вам не треба кожен раз явно передавати тип,
```suggestion
doWork. Це чудово, тому що це означає, що вам не треба кожен раз явно передавати тип,
```

2024-06-09 08:18 UTC, bulaiocht commented on _content/tour/ukr/generics-channels.article
> +вхідні параметри та тип повертаємого значення функції-робітника. WaitGroup створюється,
```suggestion
вхідні параметри та тип значення, що повертається із функції-робітника. WaitGroup створюється,
```

2024-06-09 08:18 UTC, bulaiocht commented on _content/tour/ukr/generics-channels.article
> +дозволити тому, хто викликає, завершити групу горутин і дочекатися доки всі горутини
```suggestion
дозволити тому, хто зробить її виклик, завершити групу горутин і дочекатися доки всі горутини
```

2024-06-09 08:18 UTC, bulaiocht commented on _content/tour/ukr/generics-channels.article
> +Розмір групи обчислюється враховуючи число горутин, яке може бути виконане паралельно.
```suggestion
Розмір групи обчислюється враховуючи кількість горутин, які можуть бути виконані паралельно.
```

2024-06-09 08:18 UTC, bulaiocht commented on _content/tour/ukr/generics-channels.article
> +у групу горутин. Вивід буде відрізнятися кожен раз, коли програма буде виконана,
```suggestion
у групу горутин. Вивід буде відрізнятися при кожному запуску програми,
```

2024-06-09 08:18 UTC, bulaiocht commented on _content/tour/ukr/generics-channels.article
> +Дізнайся як команда Go могла б додати пакет з конкурентними моделями у стандартну бібліотеку завдяки узагальненим типам.
```suggestion
Дізнайся як команді Go вдалося додати пакет з конкурентними моделями у стандартну бібліотеку завдяки узагальненим типам.
```

2024-06-09 08:18 UTC, bulaiocht commented on _content/tour/ukr/generics-channels.article
> +Ми написали функцію doWork, яка виконуватиме задану функцію-робітника
```suggestion
Тепер напишіть функцію doWork, яка виконуватиме задану функцію-робітник
```

2024-06-09 08:18 UTC, bulaiocht commented on _content/tour/ukr/generics-channels.article
> +повертаємий тип для функції-робітника та тип каналу.
```suggestion
тип, який повертається для функції-робітника та тип каналу.
```

2024-06-09 08:18 UTC, bulaiocht commented on _content/tour/ukr/generics-channels.article
> +У імплементації функції doWork ми використовуємо буферизований канал з
```suggestion
В імплементації функції doWork ми використовуємо буферизований канал з
```

2024-06-09 08:24 UTC, hrvadl commented on _content/tour/ukr/generics-channels.article
> +Дізнайся як команда Go могла б додати пакет з конкурентними моделями у стандартну бібліотеку завдяки узагальненим типам.
так вона ж наче не додала цей пакет? Тут у статті описується proposal

2024-06-09 09:20 UTC, hrvadl commented on _content/tour/ukr/generics-channels.article
> +Дізнайся як команда Go могла б додати пакет з конкурентними моделями у стандартну бібліотеку завдяки узагальненим типам.
@bulaiocht 🤨 🥸

2024-06-09 09:34 UTC, bulaiocht commented on _content/tour/ukr/generics-channels.article
> +Дізнайся як команда Go могла б додати пакет з конкурентними моделями у стандартну бібліотеку завдяки узагальненим типам.
@hrvadl йой, тоді моя помилка. вибачаюсь

2024-06-09 10:02 UTC, hrvadl commented on _content/tour/ukr/generics-channels.article
> +Ми написали функцію doWork, яка виконуватиме задану функцію-робітника
думаю тут краще буде `Тепер напишемо функцію`, бо цей параграфі відноситься до функції знизу

2024-06-09 10:03 UTC, hrvadl commented on _content/tour/ukr/generics-channels.article
> +Ми написали функцію doWork, яка виконуватиме задану функцію-робітника
@bulaiocht чому ти так думаєш? цей параграф відноситься до функції doWork яку вище описали. Мені здається мій варіант коректний

2024-06-09 10:20 UTC, bulaiocht commented on _content/tour/ukr/generics-channels.article
> +Ми написали функцію doWork, яка виконуватиме задану функцію-робітника
"Now write" краще перекладається як "Тепер напишемо"

2024-06-09 10:21 UTC, hrvadl commented on _content/tour/ukr/generics-channels.article
> +Ми написали функцію doWork, яка виконуватиме задану функцію-робітника
ладно, тоді добре

2024-06-09 10:50 UTC, vtopc commented on _content/tour/ukr/generics-channels.article
> +Дивись мою доповідь про узагальнені типи, в якій ми пробігаємось по всім
walk - це ж пройти/пройдемось

```suggestion
Дивись мою доповідь про узагальнені типи, в якій ми пройдемось по всім
```

2024-06-09 10:50 UTC, vtopc commented on _content/tour/ukr/generics-channels.article
> +- *Приклад* *2*: Група (Pooling)
Group - група.
Pooling - об'єднання?

2024-06-09 10:50 UTC, vtopc commented on _content/tour/ukr/generics-channels.article
> +виконаний функцією-робітником. Узагальнений тип Result визначений, щоб репрезентувати
якийсь англіцизм
```suggestion
виконаний функцією-робітником. Узагальнений тип Result визначений, щоб представити
```

2024-06-09 10:50 UTC, vtopc commented on _content/tour/ukr/generics-channels.article
> +тип, який повертається для функції-робітника та тип каналу.
якийсь відмінок не той
```suggestion
тип, який повертається для функції-робітника та типу каналу.
```
?

2024-06-09 10:50 UTC, vtopc commented on _content/tour/ukr/generics-channels.article
> +узагальненим типом Result. Цей канал повертається тому, хто викликав функцію, щоб
```suggestion
узагальненим типом Result. Це той канал, який повертається тому, хто викликав функцію, щоб
```
Чи це вже занадто дослівно?

2024-06-09 10:50 UTC, vtopc commented on _content/tour/ukr/generics-channels.article
> +отримати результат конкурентної роботи. Всередині функції, створюється горутина, щоб
"In the middle" != "inside"
```suggestion
отримати результат конкурентної роботи. В середині функції, створюється горутина, щоб
```
https://r2u.org.ua/forum/viewtopic.php?t=8592

2024-06-09 10:50 UTC, vtopc commented on _content/tour/ukr/generics-channels.article
> +Програма визначає контекст з тайм-аутом у 100 мілісекунд на старті.
```suggestion
Програма оголошує контекст з тайм-аутом у 100 мілісекунд на старті.
```
?

2024-06-09 10:50 UTC, vtopc commented on _content/tour/ukr/generics-channels.article
> +як повернути рядок "work complete". Після визначення контексту та фунції-робітника,
With - це ж разом/з.
Може, написати типу:
Контекст і фунція-робітник передається в функцію doWork?

2024-06-09 10:50 UTC, vtopc commented on _content/tour/ukr/generics-channels.article
> +Після призначення каналу з рядковим типом до змінної result, select case використовується,
Те саме.

2024-06-09 10:50 UTC, vtopc commented on _content/tour/ukr/generics-channels.article
> +Така сама ідея може бути застосована до групи горутин, які зможуть виконувати
```suggestion
Така сама ідея може бути застосована до об'єднання горутин, які зможуть виконувати
```
?

2024-06-09 10:50 UTC, vtopc commented on _content/tour/ukr/generics-channels.article
> +У цьому прикладі визначений тип репрезентує функцію, яка приймає контекст
```suggestion
У цьому прикладі оголошений тип представляє функцію, яка приймає контекст 
```

2024-06-09 10:50 UTC, vtopc commented on _content/tour/ukr/generics-channels.article
> +У функції poolWork визначено такі самі два узагальнених типа, щоб репрезентувати
```suggestion
У функції poolWork оголошені такі самі два узагальнених типа, щоб репрезентувати 
```

2024-06-09 10:50 UTC, vtopc commented on _content/tour/ukr/generics-channels.article
> +використовуючи for-range цикл для каналу. Нарешті, функція cancel створюється, щоб
```suggestion
використовуючи for-range цикл для каналу. Під кінець, функція cancel створюється, щоб
```
?

2024-06-09 10:52 UTC, hrvadl commented on _content/tour/ukr/generics-channels.article
> +- *Приклад* *2*: Група (Pooling)
так, обʼєднання горутин, було б краще.  але у тексті це вживається не як словосполучення, а просто як `обʼєднання`, що на мою думку не зовсім передає сенс без контексту, тому обрав варіант група, тому що це інтуїтивніше на мою думку

2024-06-09 10:53 UTC, hrvadl commented on _content/tour/ukr/generics-channels.article
> +виконаний функцією-робітником. Узагальнений тип Result визначений, щоб репрезентувати
так це тепер друга державна

2024-06-09 10:54 UTC, vtopc commented on _content/tour/ukr/generics-channels.article
> +- *Приклад* *2*: Група (Pooling)
Та просто група то sync.WaitGroups здебільшого.

2024-06-09 10:55 UTC, vtopc commented on _content/tour/ukr/generics-channels.article
> +виконаний функцією-робітником. Узагальнений тип Result визначений, щоб репрезентувати
Так нащо ми тоді перекладаємо pool/pooling?

2024-06-09 10:56 UTC, hrvadl commented on _content/tour/ukr/generics-channels.article
> +Дивись мою доповідь про узагальнені типи, в якій ми пробігаємось по всім
так, але на український лад пробіжимось/пройдемось у сенсі `розглянути щось` має однакове значення, принаймні я так думаю, але я хз бо я не лінгвіст

2024-06-09 10:57 UTC, hrvadl commented on _content/tour/ukr/generics-channels.article
> +виконаний функцією-робітником. Узагальнений тип Result визначений, щоб репрезентувати
так англіцизм це словникове мовне запозичення з іншої мови, слово репрезентувати є в українській мові, а слово `пулінг` навряд

2024-06-09 10:58 UTC, hrvadl commented on _content/tour/ukr/generics-channels.article
> +узагальненим типом Result. Цей канал повертається тому, хто викликав функцію, щоб
мені здається таке формулювання трохи ускладнює і без того не просте речення

2024-06-09 10:59 UTC, hrvadl commented on _content/tour/ukr/generics-channels.article
> +як повернути рядок "work complete". Після визначення контексту та фунції-робітника,
тут наче не просто with, a with <smthng> and <smthng> **in place**
що дослівно перекладається як з чимось на чимось на місці

2024-06-09 11:01 UTC, hrvadl commented on _content/tour/ukr/generics-channels.article
> +як повернути рядок "work complete". Після визначення контексту та фунції-робітника,
що дослівно у нашому випадку перекладається як
`З визначеним контекстом і функцією-робітником на місці`

але мені здається це не зовсім на наш лад, тому спростив це перевівши не дослівно, але сенс наче той самий

2024-06-09 11:02 UTC, bulaiocht commented on _content/tour/ukr/generics-channels.article
> +виконаний функцією-робітником. Узагальнений тип Result визначений, щоб репрезентувати
тоді мабуть буде доречно писати `пул` та `обʼєднання в пул`

2024-06-09 11:03 UTC, hrvadl commented on _content/tour/ukr/generics-channels.article
> +Така сама ідея може бути застосована до групи горутин, які зможуть виконувати
так, тут то воно звучить класно. Але в інших місцях воно використовується не як `обʼєднання горутин`, а просто як `обʼєднання`

2024-06-09 11:05 UTC, hrvadl commented on _content/tour/ukr/generics-channels.article
> +Така сама ідея може бути застосована до групи горутин, які зможуть виконувати
ладно, пофіг, хай буде дослівно як 'обʼєднанняʼ

2024-06-09 11:10 UTC, hrvadl commented on _content/tour/ukr/generics-channels.article
> +як повернути рядок "work complete". Після визначення контексту та фунції-робітника,
@vtopc теоретично це можна перекласти як
`Маючи контекст та функцію-робітиника`

2024-06-09 11:11 UTC, hrvadl commented on _content/tour/ukr/generics-channels.article
> +як повернути рядок "work complete". Після визначення контексту та фунції-робітника,
це як варіант

2024-06-09 11:12 UTC, hrvadl commented on _content/tour/ukr/generics-channels.article
> +виконаний функцією-робітником. Узагальнений тип Result визначений, щоб репрезентувати
@bulaiocht я вже поміняв на просто `обʼєднання`, хай буде так

2024-06-09 11:16 UTC, hrvadl commented on _content/tour/ukr/generics-channels.article
> +узагальненим типом Result. Цей канал повертається тому, хто викликав функцію, щоб
@vtopc пропоную залишити так як є тут

2024-06-09 11:30 UTC, hrvadl commented on _content/tour/ukr/generics-channels.article
> +Після призначення каналу з рядковим типом до змінної result, select case використовується,
@vtopc як тобі альтернативні варіанти у коментарі вище?

2024-06-09 11:43 UTC, vtopc commented on _content/tour/ukr/generics-channels.article
> +Дивись мою доповідь про узагальнені типи, в якій ми пробігаємось по всім
Ні, пройдемост - це розглянемо детальніше, а пробіжимось - це розглянемо поверхнево.

2024-06-09 11:46 UTC, vtopc commented on _content/tour/ukr/generics-channels.article
> +узагальненим типом Result. Цей канал повертається тому, хто викликав функцію, щоб
ОК

2024-06-09 11:47 UTC, vtopc commented on _content/tour/ukr/generics-channels.article
> +як повернути рядок "work complete". Після визначення контексту та фунції-робітника,
> @vtopc теоретично це можна перекласти як
> `Маючи контекст та функцію-робітиника`
> або
> `З наявним контекстом та функцією-робітником`

Так, так краще звучить.

2024-06-09 11:47 UTC, hrvadl commented on _content/tour/ukr/generics-channels.article
> +Дивись мою доповідь про узагальнені типи, в якій ми пробігаємось по всім
я вже виправив

2024-06-09 11:58 UTC, hrvadl commented
@bulaiocht @vtopc всі зауваження виправлені, чекаю на апрув якщо більше нема зауважень.
Також було б непогано якщо б @bulaiocht попросив би write permission до цього репозиторія у @vpakhuchyi, бо без write permissionʼа твої ревʼю не рахууються :)

2024-06-09 15:54 UTC, vtopc approved these changes

2024-06-09 15:54 UTC, vtopc commented on _content/tour/ukr/generics-channels.article
> +Потім визначається функція-робітник, яка чекатиме 200 мілісекунд перед тим,
```suggestion
Потім оголошується функція-робітник, яка чекатиме 200 мілісекунд перед тим,
```
?

2024-06-10 13:52 UTC, bulaiocht approved these changes

2024-06-12 09:02 UTC, merged