type conversion and assertion article translated
GolangUA/ardanlabs-gotour pull request #5
Opened 2024-06-11 13:41 UTC by girthybean

composition-assertions.article file translated

2024-06-11 13:57 UTC, vtopc commented on _content/tour/ukr/composition-assertions.article
> +Приведення та Припущення типів
В Go Tour ми назвали Assertions - "Твердження" 🤯 
https://go-tour-ua-translation.lm.r.appspot.com/methods/15

2024-06-11 13:57 UTC, vtopc commented on _content/tour/ukr/composition-assertions.article
> +** Ревʼю коду
Якийсь англіцизм...

2024-06-11 13:57 UTC, vtopc commented on _content/tour/ukr/composition-assertions.article
> +Припустимо, програма декларує два типи, що звуться Car та Cloud,
```suggestion
Припустимо, програма оголошує два типи, що звуться Car та Cloud,
```

2024-06-11 13:57 UTC, vtopc commented on _content/tour/ukr/composition-assertions.article
> +Ви можете створити значення типу MoveLocker та Mover з нульовим початковим станом.
В одному місці "ти", в іншому "ви".

2024-06-11 13:57 UTC, vtopc commented on _content/tour/ukr/composition-assertions.article
> +кожен з яких імплементує інтерфейс fmt.Stringer, ви можете створити колекцію,
Знову "ви".

2024-06-11 13:59 UTC, hrvadl commented on _content/tour/ukr/composition-assertions.article
> +** Ревʼю коду
я так само перекладав :)

2024-06-11 14:01 UTC, girthybean commented on _content/tour/ukr/composition-assertions.article
> +Приведення та Припущення типів
тоді мені треба це поправити всюду

2024-06-11 14:04 UTC, bulaiocht commented on _content/tour/ukr/composition-assertions.article
> +Приведення та Припущення типів
@vtopc поправив

2024-06-11 14:05 UTC, vtopc commented on _content/tour/ukr/composition-assertions.article
> +** Ревʼю коду
Так само як де?

2024-06-11 14:07 UTC, bulaiocht commented on _content/tour/ukr/composition-assertions.article
> +кожен з яких імплементує інтерфейс fmt.Stringer, ви можете створити колекцію,
@vtopc мені подобається "ви"

2024-06-11 14:08 UTC, girthybean commented on _content/tour/ukr/composition-assertions.article
> +** Ревʼю коду
@vtopc чи є в нас десь глосарій? було б добре мати список узгоджених термінів, щоб не було розбіжностей по документах

2024-06-11 14:12 UTC, bulaiocht commented on _content/tour/ukr/composition-assertions.article
> +Припустимо, програма декларує два типи, що звуться Car та Cloud,
@vtopc але ж при цьому "декларативне програмування" або "декларація функції"

2024-06-11 14:13 UTC, vtopc commented on _content/tour/ukr/composition-assertions.article
> +кожен з яких імплементує інтерфейс fmt.Stringer, ви можете створити колекцію,
ОК. Тоді "Ви".

2024-06-11 14:15 UTC, vtopc commented on _content/tour/ukr/composition-assertions.article
> +Припустимо, програма декларує два типи, що звуться Car та Cloud,
Ну в іншому PR так - https://github.com/GolangUA/ardanlabs-gotour/pull/4/files?w=1#diff-6863292b10111e468aabc09f34723bbe32758813b69f8cf3a3ea4e0e7b9d8923R29

2024-06-11 14:15 UTC, vtopc commented on _content/tour/ukr/composition-assertions.article
> +** Ревʼю коду
Нема. Напевно, треба зробити.

2024-06-11 14:18 UTC, bulaiocht commented on _content/tour/ukr/composition-assertions.article
> +** Ревʼю коду
@vtopc додав табу в той документ де ми записуємо хто шо робить. треба туди занести всі терміни, які викликають більше всього сперечань.

2024-06-11 14:20 UTC, vtopc commented on _content/tour/ukr/composition-assertions.article
> +кожен з яких імплементує інтерфейс fmt.Stringer, ви можете створити колекцію,
Хоча, в іншому PR "ти" - https://github.com/GolangUA/ardanlabs-gotour/pull/5/files?w=1#diff-fe124e2366626944565c52d5d08bf18a00843dde8d199e6a61c715e5b56cd5d0R2

2024-06-11 14:22 UTC, bulaiocht commented on _content/tour/ukr/composition-assertions.article
> +кожен з яких імплементує інтерфейс fmt.Stringer, ви можете створити колекцію,
тоді це теж треба в глосарій...

2024-06-12 07:25 UTC, bulaiocht commented on _content/tour/ukr/composition-assertions.article
> +** Ревʼю коду
Міняю на "Перегляд"

2024-06-12 08:22 UTC, hrvadl requested changes

2024-06-12 08:22 UTC, hrvadl commented on _content/tour/ukr/composition-assertions.article
> +- Якщо потрібна фінансова допомога, то використовуй [[https://www.ardanlabs.com/scholarship/][Форму для отримання стипендії]]
я ось тут завжди `форму` писав з маленької літери, треба узгодити єдиний варіант

2024-06-12 08:22 UTC, hrvadl commented on _content/tour/ukr/composition-assertions.article
> +Приведення типів дозволяє змінити дані одного типу в інший.
```suggestion
Приведення типів дозволяє перетворити дані одного типу в інший.
```

2024-06-12 08:22 UTC, hrvadl commented on _content/tour/ukr/composition-assertions.article
> +Як ви могли побачити в попередньому прикладі, значення інтерфейсу одного типу може бути предано,
в оригіналі цей параграф займає 5 рядків, а у тебе 4. Давай +- робити рядки як в оригіналі де це можливо

2024-06-12 08:22 UTC, hrvadl commented on _content/tour/ukr/composition-assertions.article
> +Ви можете створити значення типу MoveLocker та Mover з нульовим початковим станом.
гарне зауваження було від @vtopc стосовно використання `ви` та `ти`. Я нажаль теж не дотримувався якоїсь конвенції. Давай узгодимо як ми перекладатимо такі моменти, треба обрати один варіант

2024-06-12 08:22 UTC, hrvadl commented on _content/tour/ukr/composition-assertions.article
> +Друга форма твердження типів в даному випадку вирішальна.
додай нову лінію)

2024-06-12 08:26 UTC, hrvadl commented on _content/tour/ukr/composition-assertions.article
> +** Ревʼю коду
@bulaiocht я тоді в своїх ПР теж поправлю

2024-06-12 08:27 UTC, hrvadl commented on _content/tour/ukr/composition-assertions.article
> +кожен з яких імплементує інтерфейс fmt.Stringer, ви можете створити колекцію,
все, визначился з цим, тепер всюди буде "ви". я у себе теж поправлю
@vtopc

2024-06-12 08:39 UTC, bulaiocht commented on _content/tour/ukr/composition-assertions.article
> +Ви можете створити значення типу MoveLocker та Mover з нульовим початковим станом.
узгоджено

2024-06-12 08:39 UTC, bulaiocht commented on _content/tour/ukr/composition-assertions.article
> +Як ви могли побачити в попередньому прикладі, значення інтерфейсу одного типу може бути предано,
відформатовано

2024-06-12 08:40 UTC, girthybean commented on _content/tour/ukr/composition-assertions.article
> +- Якщо потрібна фінансова допомога, то використовуй [[https://www.ardanlabs.com/scholarship/][Форму для отримання стипендії]]
зробив теж маленькою, бо тоді читається нормально

2024-06-12 08:55 UTC, hrvadl approved these changes
LGTM

2024-06-12 11:50 UTC, vtopc commented on _content/tour/ukr/composition-assertions.article
> +- Якщо потрібна фінансова допомога, то використовуй [[https://www.ardanlabs.com/scholarship/][форму для отримання стипендії]]
```suggestion
- Якщо потрібна фінансова допомога, то використовуйте [[https://www.ardanlabs.com/scholarship/][форму для отримання стипендії]]
```

2024-06-12 11:50 UTC, vtopc commented on _content/tour/ukr/composition-assertions.article
> +Приведення типів дозволяє перетворити дані одного типу в інший.
конвертація? https://go-tour-ua-translation.lm.r.appspot.com/basics/13

2024-06-12 11:50 UTC, vtopc commented on _content/tour/ukr/composition-assertions.article
> +Ви можете створити значення типу MoveLocker та Mover з нульовим початковим станом.
Може трохи простіше?
```suggestion
Ви можете створити значення типу MoveLocker та Mover з нульовим значенням.
```
https://go-tour-ua-translation.lm.r.appspot.com/basics/12

2024-06-12 11:50 UTC, vtopc commented on _content/tour/ukr/composition-assertions.article
> +Ці властивості інтерфейсів є насправді безцінними.
values - це значення;

безцінний - дорогий; цінний, коштовний,
тут valueless мається на увазі як zero value.

```suggestion
Ці значення інтерфейсів насправді не мають значення.
```
?

2024-06-12 11:50 UTC, vtopc commented on _content/tour/ukr/composition-assertions.article
> +Потім ви можете створити значення типу bike з нульовим початковим станом
Те саме

2024-06-12 11:50 UTC, vtopc commented on _content/tour/ukr/composition-assertions.article
> +певного типу в середині інтерфейсу. Ви можете подивитися це за допомогою m.(bike) синтаксису
```suggestion
певного типу всередині інтерфейсу. Ви можете подивитися це за допомогою синтаксису m.(bike)
```
https://r2u.org.ua/forum/viewtopic.php?t=8592

2024-06-12 12:07 UTC, vtopc commented on _content/tour/ukr/composition-assertions.article
> +* Приведення та Твердження типів
```suggestion
* Конвертація та Твердження типів
```
https://go-tour-ua-translation.lm.r.appspot.com/basics/13

2024-06-12 12:35 UTC, bulaiocht commented on _content/tour/ukr/composition-assertions.article
> +* Приведення та Твердження типів
Приведення/Перетворення типів дуже поширений термін в інших мовах програмування

2024-06-12 17:33 UTC, vtopc commented on _content/tour/ukr/composition-assertions.article
> +* Приведення та Твердження типів
OK

2024-06-12 17:40 UTC, vtopc approved these changes

2024-06-12 17:40 UTC, vtopc commented on _content/tour/ukr/composition-assertions.article
> +** Неявне конвертація інтерфейсів
```suggestion
** Неявна конвертація інтерфейсів
```

2024-06-12 17:40 UTC, vtopc commented on _content/tour/ukr/composition-assertions.article
> +Це значення інтерфейсу, які насправді не мають значення.
Сорі, неправильно, переклав, тут в множині:
```suggestion
Ці значення інтерфейсу насправді не мають значення.
```

2024-06-12 19:13 UTC, bulaiocht commented on _content/tour/ukr/composition-assertions.article
> +Ці властивості інтерфейсів є насправді безцінними.
@vtopc виправив

2024-06-12 20:01 UTC, abagayev commented on _content/tour/ukr/composition-assertions.article
> +Конвертація та Твердження типів
Тут або нижче чи треба додати в дужечках оригінальну назву, бо це перша згадка?

2024-06-12 20:04 UTC, abagayev commented on _content/tour/ukr/composition-assertions.article
> +Вивід:
хммммм

```suggestion
Висновок:
```

2024-06-12 20:04 UTC, abagayev commented on _content/tour/ukr/composition-assertions.article
> +осклільки компілятор має можливість гарантувати тільки те, що конкретне значення,
```suggestion
оскільки компілятор має можливості гарантувати тільки те, що конкретне значення,
```

2024-06-13 06:44 UTC, girthybean commented on _content/tour/ukr/composition-assertions.article
> +Вивід:
Тут мається на увазі консольний вивід

2024-06-13 06:50 UTC, bulaiocht commented on _content/tour/ukr/composition-assertions.article
> +осклільки компілятор має можливість гарантувати тільки те, що конкретне значення,
Тайпо виправлю. У випадку із можливістю або можливостями, на мою думку, компілятор має багато можливостей але тут йдеться про одну конкретну, тому "можливість". Як вважаєш?

2024-06-13 15:25 UTC, hrvadl commented on _content/tour/ukr/composition-assertions.article
> +Вивід:
@bulaiocht так, думаю можна цей комент резолвати

2024-06-13 15:28 UTC, bulaiocht commented on _content/tour/ukr/composition-assertions.article
> +Конвертація та Твердження типів
додав

2024-06-13 15:34 UTC, bulaiocht commented on _content/tour/ukr/composition-assertions.article
> +осклільки компілятор має можливість гарантувати тільки те, що конкретне значення,
виправив

2024-06-13 15:37 UTC, merged