translated goroutines article
GolangUA/ardanlabs-gotour pull request #8
Opened 2024-06-16 12:08 UTC by hrvadl

2024-06-16 15:46 UTC, bulaiocht requested changes
Треба трохи поправити та можливо перефразувати

2024-06-16 15:46 UTC, girthybean commented on _content/tour/ukr/goroutines.article
> +скільки потоків операційної системи може бути виконано паралельно. Це засновано на кількості
```suggestion
скільки потоків операційної системи може бути виконано паралельно. Це рішення базується на кількості
```

2024-06-16 15:46 UTC, girthybean commented on _content/tour/ukr/goroutines.article
> +виконання створює потік операційної системи (М) і прикриплює його до структури даних, яка
```suggestion
виконання створює потік операційної системи (М) і прикріплює його до структури даних, яка
```

2024-06-16 15:46 UTC, girthybean commented on _content/tour/ukr/goroutines.article
> +здатність або контекст виконання для виконання програми Go.
```suggestion
здатність або контекст виконання для середи виконання програми Go.
```

2024-06-16 15:46 UTC, girthybean commented on _content/tour/ukr/goroutines.article
> +обраних M/P. Так само, як M управляє виконанням інструкцій заліза,
```suggestion
на обраних M/P. Так само, як M управляє виконанням інструкцій заліза, 
```

2024-06-16 15:46 UTC, girthybean commented on _content/tour/ukr/goroutines.article
> +системи, проте передає контроль виконання на рівень застосунку.
```suggestion
G управляє виконанням інструкцій M. Це створює новий шар абстракції поверх операційної
системи, проте передає контроль виконання на рівень застосунку.
```

2024-06-16 15:46 UTC, girthybean commented on _content/tour/ukr/goroutines.article
> +Планувальник операційної системи виконує роботу створення іллюзії, що декілька
```suggestion
Планувальник операційної системи має задачу створити іллюзію, що декілька
```

2024-06-16 15:46 UTC, girthybean commented on _content/tour/ukr/goroutines.article
> +виконується потоками, яких додаток може мати від одного і більше.
```suggestion
*Робота:* Набір інструкцій, які необхідно виконати для роботи застосунку. Ці
інструкції виконуються потоками, яких додаток може мати від одного і більше.
```

2024-06-16 15:46 UTC, girthybean commented on _content/tour/ukr/goroutines.article
> +інструкцій заліза.
```suggestion
інструкцій на апаратному рівні.
```

2024-06-16 15:46 UTC, girthybean commented on _content/tour/ukr/goroutines.article
> +значить що потік не важливий для планувальника.
```suggestion
*Стани* *потока:* Поток може бути в одному з трьох станів: *Виконується*, *Запущений*
або *Очікує*. *Виконується* - значить, що потік виконує призначені інструкції на
залізі, маючи G розташовану на M. *Запущений* - значить, що потік потребує апаратний час, щоб
виконати призначенні йому інструкції, та сидить в черзі виконання. *Очікує* -
значить, що потік чекає на щось, перед тим як продовжити свою роботу. 
Планувальник не займаєтсья потоками в стані *Очікує*.
```

2024-06-16 15:46 UTC, girthybean commented on _content/tour/ukr/goroutines.article
> +виконання роботи неважливий, до тих пір, доки вся робота виконана.
```suggestion
виконання роботи неважливий, до тих пір, доки вся робота не виконана.
```

2024-06-16 15:46 UTC, girthybean commented on _content/tour/ukr/goroutines.article
> +*Паралелізм:* Це значить робити багато речей одночасно. Щоб це було можливо, треба
```suggestion
*Паралелізм:* Це значить робити багато речей одночасно. Щоб досягти цього, треба
```

2024-06-16 15:46 UTC, girthybean commented on _content/tour/ukr/goroutines.article
> +розцінено як робота вводу/виводу.
```suggestion
у стан очікування. Наприклад, отримання даних з різних адрес ресурсів (URL) може
вважатися роботою вводу/виводу.
```

2024-06-16 15:46 UTC, girthybean commented on _content/tour/ukr/goroutines.article
> +які важко знайти.
```suggestion
*Синхронізація:* Коли дві або більше горутини потребують доступ до тієї самої локації
памʼяті в один і той самий час, то їх потрібно синхронізувати та чергувати.
Якщо синхронізація не відбувається і хоча б одна з горутин виконує запис даних, то це приводить до гонитви даних (data races). Гонитва даних є причиною багатьох багів з пошкодженням даних,
які важко знайти.
```

2024-06-16 15:46 UTC, girthybean commented on _content/tour/ukr/goroutines.article
> +які важко знайти.
[Стан гонитви](https://uk.wikipedia.org/wiki/%D0%A1%D1%82%D0%B0%D0%BD_%D0%B3%D0%BE%D0%BD%D0%B8%D1%82%D0%B2%D0%B8)

2024-06-16 15:46 UTC, girthybean commented on _content/tour/ukr/goroutines.article
> +Це може стати причиною всіляких багів з пошкодженням даних.
```suggestion
*Оркестрування:* Коли двом або більше горутинам потрібно просигналізувати одна одній
з або без даних, необхідно мати механіку оркестрації. Без оркестрації
будь-які гарантії щодо виконання і завершення конкурентної роботи будуть втрачені.
Це може стати причиною всіляких багів із пошкодженням даних.
```

2024-06-16 15:46 UTC, girthybean commented on _content/tour/ukr/goroutines.article
> +більше читайте три пости у главі 14, яка зветься Планування у Go.
```suggestion
Є багато дрібних деталей, повʼязаних із семантикою планувальника, тому, щоб дізнатися
більше, читайте три пости у главі 14, яка зветься Планування у Go.
```

2024-06-16 15:46 UTC, bulaiocht commented on _content/tour/ukr/goroutines.article
> +** Основа конкурентності
```suggestion
** Основи конкурентності
```

2024-06-16 15:46 UTC, bulaiocht commented on _content/tour/ukr/goroutines.article
> +Все ж таки виклик функції перепише змінну.
```suggestion
Однак виклик цієї функції перепише змінну.
```

2024-06-16 15:46 UTC, bulaiocht commented on _content/tour/ukr/goroutines.article
> +так і виклик функції, щоб усe співставити.
```suggestion
Ця функція дуже важлива при налаштуванні квот процесора у конфігурації контейнера.
Коли передається 0, то звітується число потоків, які використовуватиме Go  програма.
Ви повинні впевнитися в тому, що це число співпадає з числом потоків операційної системи, 
які доступні у вашому контейнерізованому середовищі. Якщо числа не співпадуть, то програма Go
не працюватиме так добре, як могла би. Ви можете використовувати як змінну оточення, 
так і виклик функції, щоб усe співставити.
```

2024-06-16 18:06 UTC, alexandear requested changes
Please consider using a basic spell checker, such as Google Docs, to identify and correct any typos.

2024-06-16 18:06 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +Планувальник операційної системи має задачу створити іллюзію, що декілька
```suggestion
Планувальник операційної системи має задачу створити ілюзію, що декілька
```

2024-06-16 18:06 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +Це вимагає деяких компромісів у дизайні планувальника. Перед тим, як заглибоюватися
```suggestion
Це вимагає деяких компромісів у дизайні планувальника. Перед тим, як заглиблюватися
```

2024-06-16 18:06 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +*Стани* *потока:* Поток може бути в одному з трьох станів: *Виконується*, *Запущений*
```suggestion
*Стани* *потоку:* Потік може бути в одному з трьох станів: *Виконується*, *Запущений*
```

Відмінювання ["Потік"](https://goroh.pp.ua/%D0%A1%D0%BB%D0%BE%D0%B2%D0%BE%D0%B7%D0%BC%D1%96%D0%BD%D0%B0/%D0%9F%D0%BE%D1%82%D1%96%D0%BA)

2024-06-16 18:06 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +*Стани* *потока:* Поток може бути в одному з трьох станів: *Виконується*, *Запущений*
Зміни, будь ласка, у всьому документі:

- "поток" -> "потік"
- "потока" -> "потоку"

2024-06-16 18:06 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +Планувальник не займаєтсья потоками в стані *Очікує*.
```suggestion
Планувальник не займається потоками в стані *Очікує*.
```

2024-06-16 18:06 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +*Конкурентність:* Це значить невизначенність порядку виконання. Іншими словами,
З однією "н":

```suggestion
*Конкурентність:* Це значить невизначеність порядку виконання. Іншими словами,
```

https://slovnyk.ua/index.php?swrd=%D0%BD%D0%B5%D0%B2%D0%B8%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D1%96%D1%81%D1%82%D1%8C

2024-06-16 18:06 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +мати можливіть виконувати два або більше потока операційної системи одночасно
```suggestion
мати можливість виконувати два або більше потоків операційної системи одночасно
```

2024-06-16 18:06 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +у стан очікування. Наприклад, обчислення числа фібоначчі можна вважати роботою процесора.
```suggestion
у стан очікування. Наприклад, обчислення числа Фібоначчі можна вважати роботою процесора.
```

https://uk.wikipedia.org/wiki/%D0%9F%D0%BE%D1%81%D0%BB%D1%96%D0%B4%D0%BE%D0%B2%D0%BD%D1%96%D1%81%D1%82%D1%8C_%D0%A4%D1%96%D0%B1%D0%BE%D0%BD%D0%B0%D1%87%D1%87%D1%96

2024-06-16 18:06 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +тим самим програма заввершиться.
```suggestion
тим самим програма завершиться.
```

2024-06-16 18:06 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +Коли ви зкомпілюєте та запустите цю програму, ви побачитe, як вона виконується конкурентно.
```suggestion
Коли ви скомпілюєте та запустите цю програму, ви побачитe, як вона виконується конкурентно.
```

https://goroh.pp.ua/%D1%82%D0%BB%D1%83%D0%BC%D0%B0%D1%87%D0%B5%D0%BD%D0%BD%D1%8F/%D1%81%D0%BA%D0%BE%D0%BC%D0%BF%D1%96%D0%BB%D1%8E%D0%B2%D0%B0%D1%82%D0%B8

2024-06-16 18:06 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +Програма може виконати лише одну з двох горутин, або взагалі завершити виконнання одразу.
```suggestion
Програма може виконати лише одну з двох горутин, або взагалі завершити виконання одразу.
```

2024-06-16 18:06 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +достатьно часу, щоб закінчити повністю за один проміжок часу.
```suggestion
достатньо часу, щоб закінчити повністю за один проміжок часу.
```

2024-06-16 18:06 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +Конкуретність повинна залишатися невизначеною, і ви маєте про це памʼятати, коли
```suggestion
Конкурентність повинна залишатися невизначеною, і ви маєте про це памʼятати, коли
```

2024-06-16 18:06 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +- Конкуретність - це мати справу з багаться речами водночас.
```suggestion
- Конкурентність - це мати справу з багатьма речами водночас.
```

2024-06-16 18:06 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +"Паралелізм - це коли дві або більше речі фізично робляться одночасно. Конкурентність це невизначене, невпорядковане виконнання." - William Kennedy
```suggestion
"Паралелізм - це коли дві або більше речі фізично робляться одночасно. Конкурентність це невизначене, невпорядковане виконання." - William Kennedy
```

2024-06-16 18:06 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +*Частина* *A* Cтворіть програму, яка визначає дві анонімних функції. Одну, яка рахуватме від 100 до 0,
```suggestion
*Частина* *A* Cтворіть програму, яка визначає дві анонімних функції. Одну, яка рахуватиме від 100 до 0,
```

2024-06-16 18:06 UTC, alexandear requested changes
Please consider using a basic spell checker, such as Google Docs, to identify and correct any typos.

2024-06-16 20:36 UTC, vtopc commented on _content/tour/ukr/goroutines.article
> +Горутини
Трохи навпаки.
```suggestion
Горутини (Goroutines)
```

2024-06-16 20:36 UTC, vtopc commented on _content/tour/ukr/goroutines.article
> +* Горутини (Goroutines)
```suggestion
* Горутини
```

2024-06-16 20:36 UTC, vtopc commented on _content/tour/ukr/goroutines.article
> +виконання роботи неважливий, до тих пір, доки вся робота не виконана.
```suggestion
виконання роботи неважливий, до тих пір, доки вся робота не буде виконана.
```

2024-06-16 20:36 UTC, vtopc commented on _content/tour/ukr/goroutines.article
> +які важко знайти.
@bulaiocht , data race - це не стан гонитви - https://uk.wikipedia.org/wiki/%D0%A1%D1%82%D0%B0%D0%BD_%D0%B3%D0%BE%D0%BD%D0%B8%D1%82%D0%B2%D0%B8#Data_race

2024-06-16 20:36 UTC, vtopc commented on _content/tour/ukr/goroutines.article
> +Функція пишеться великими літерами, тому що це також є змінна оточення.
capitalized - це вже доконана дія.
```suggestion
Назва функція написана великими літерами, тому що це також є змінна оточення.
```

2024-06-16 20:36 UTC, vtopc commented on _content/tour/ukr/goroutines.article
> +Коли передається 0, то звітується число потоків, які використовуватиме Go  програма.
```suggestion
При передачі 0 вертається кількість потоків, які буде використовувати Go програма.
```
Хоча в https://pkg.go.dev/runtime#GOMAXPROCS взагалі пише "returns the previous setting"...

2024-06-16 20:36 UTC, vtopc commented on _content/tour/ukr/goroutines.article
> +виклик до функції Done. Цей виклик декрементує значення WaitGroup на 1. Коли обидва
```suggestion
виклик до функції Done. Цей виклик зменшує значення WaitGroup на 1. Коли обидва
```

2024-06-16 20:36 UTC, vtopc commented on _content/tour/ukr/goroutines.article
> +головній горутині буде дозволено розблокуватися від виклику Wait,
вище писали[ "горутина main"](https://github.com/GolangUA/ardanlabs-gotour/pull/8/files?w=1#diff-79f8325eaba02f3dacd3081018a2507fc3a11a88162167e7bf54f575f0245b5aR148), а тут тепер перекладаємо

2024-06-16 20:36 UTC, vtopc commented on _content/tour/ukr/goroutines.article
> +в одному полі зору. Намагайтеся не передавати WaitGroup як параметр у функцію,
```suggestion
в одній зоні видимості. Намагайтеся не передавати WaitGroup як параметр у функцію,
```
Сподіваюсь такий варіант не натякає на scoup?

2024-06-16 20:36 UTC, vtopc commented on _content/tour/ukr/goroutines.article
> +перед тим як програма завершилася. Наступний раз, коли ви запустите цю програму, не буде
```suggestion
перед тим як програма завершилася. Наступного разу, коли ви запустите цю програму, не буде
```

2024-06-16 20:36 UTC, vtopc commented on _content/tour/ukr/goroutines.article
> +гарантії, що ви отримаєте такий самий результат. Єдина гарантія - це те, програма не завершить
```suggestion
гарантії, що ви отримаєте такий самий результат. Єдина гарантія - це те, що програма не завершить
```

2024-06-17 06:13 UTC, hrvadl commented on _content/tour/ukr/goroutines.article
> +головній горутині буде дозволено розблокуватися від виклику Wait,
@vtopc так, треба поправити напевно на головну горутину всюди

2024-06-17 06:14 UTC, hrvadl commented on _content/tour/ukr/goroutines.article
> +в одному полі зору. Намагайтеся не передавати WaitGroup як параметр у функцію,
мені здається трохи натякає

2024-06-17 06:20 UTC, bulaiocht commented on _content/tour/ukr/goroutines.article
> +які важко знайти.
Так, але саме слово "гонитва" думаю підходить

2024-06-17 13:38 UTC, vtopc commented on _content/tour/ukr/goroutines.article
> +в одному полі зору. Намагайтеся не передавати WaitGroup як параметр у функцію,
OK

2024-06-17 13:40 UTC, vtopc commented on _content/tour/ukr/goroutines.article
> +які важко знайти.
Гонитва даних?

2024-06-17 22:07 UTC, abagayev requested changes
Чудова робота! Ще трохи треба підфіксити.

2024-06-17 22:07 UTC, abagayev commented on _content/tour/ukr/goroutines.article
> +G управляє виконанням інструкцій M. Це створює новий шар абстракції поверх операційної
Мені здається це русизм, словник каже що "поверх" рідко означає "понад":
https://slovnyk.ua/index.php?swrd=%D0%BF%D0%BE%D0%B2%D0%B5%D1%80%D1%85

Схоже це і правда не сильно використовується саме так:
https://www.google.com/search?q=%22%D0%B0%D0%B1%D1%81%D1%82%D1%80%D0%B0%D0%BA%D1%86%D1%96%D1%8F+%D0%BF%D0%BE%D0%B2%D0%B5%D1%80%D1%85%22+lang%3Aua

Тож мені здається, краще сказати _над_ операційною системою.

2024-06-17 22:07 UTC, abagayev commented on _content/tour/ukr/goroutines.article
> +*Стани* *потоку:* Потік може бути в одному з трьох станів: *Виконується*, *Запущений*
Тут в оригіналі назви станів без курсива, це спеціально чи випадково у тебе додався курсив?

2024-06-17 22:07 UTC, abagayev commented on _content/tour/ukr/goroutines.article
> +виконання повного набору інструкцій у будь якому невизначеному порядку приводить до того
https://onlinecorrector.com.ua/uk/%D0%B1%D1%83%D0%B4%D1%8C-%D1%8F%D0%BA%D0%B8%D0%B9/

```suggestion
виконання повного набору інструкцій у будь-якому невизначеному порядку приводить до того
```

2024-06-17 22:07 UTC, abagayev commented on _content/tour/ukr/goroutines.article
> +у стан очікування. Наприклад, отримання даних з різних адрес ресурсів (URL) може
Адрес ресурсів це коректний переклад, але може просто посилання? :-)

2024-06-17 22:07 UTC, abagayev commented on _content/tour/ukr/goroutines.article
> +*Оркестрування:* Коли двом або більше горутинам потрібно просигналізувати одна одній
Тут кома здається важливою

```suggestion
*Оркестрування:* Коли двом або більше горутинам потрібно просигналізувати одна одній,
```

2024-06-17 22:07 UTC, abagayev commented on _content/tour/ukr/goroutines.article
> +Виклик до GOMAXPROCS робиться щоб виконати Go програму в одному потоці.
Вимбачте, трохи ще понабридаю з комою

https://www.miyklas.com.ua/p/ukrainska-mova/9-klas/skladnopidriadne-rechennia-43534/spr-z-pidriadnimi-obstavinnimi-umovi-meti-prichini-naslidkovimi-i-dopusto_-45320/re-b8d0bf78-9283-424a-bd15-84bae704762f

```suggestion
Виклик до GOMAXPROCS робиться, щоб виконати Go програму в одному потоці.
```

2024-06-17 22:07 UTC, abagayev commented on _content/tour/ukr/goroutines.article
> +Назва функція написана великими літерами, тому що це також є змінна оточення.
```suggestion
Назва функції написана великими літерами, тому що це також є змінною оточення.
```

2024-06-17 22:07 UTC, abagayev commented on _content/tour/ukr/goroutines.article
> +які доступні у вашому контейнерізованому середовищі. Якщо числа не співпадуть, то програма Go
https://kubernetes.io/uk/docs/tutorials/kubernetes-basics/

```suggestion
які доступні у вашому контейнеризованому середовищі. Якщо числа не співпадуть, то програма Go
```

2024-06-17 22:07 UTC, abagayev commented on _content/tour/ukr/goroutines.article
> +main повернутися, доки не буде гарантії, що дві створені горутини завершать своє
Мені схоже на сильно дослівний переклад слова "return", може отак?

```suggestion
main завершитися, доки не буде гарантії, що дві створені горутини завершать своє
```

2024-06-17 22:07 UTC, abagayev commented on _content/tour/ukr/goroutines.article
> +виконання спочатку. WaitGroup це чудовий інструмент для вирішення проблем оркестрації,
"спочатку" я б теж переніс раніше: ... горутини спочатку завершать ...

2024-06-17 22:07 UTC, abagayev commented on _content/tour/ukr/goroutines.article
> +важливо. Виклик Wait блокуватиме, доки WaitGroup не встановить своє значення назад
управління [...] важливе

```suggestion
важливе. Виклик Wait блокуватиме, доки WaitGroup не встановить своє значення назад
```

2024-06-17 22:07 UTC, abagayev commented on _content/tour/ukr/goroutines.article
> +виклик до функції Done. Цей виклик зменшує значення WaitGroup на 1. Коли обидва
Оригінал корявий, я б замість to використав of :-)

```suggestion
виклик функції Done. Цей виклик зменшує значення WaitGroup на 1. Коли обидва
```

2024-06-17 22:07 UTC, abagayev commented on _content/tour/ukr/goroutines.article
> +Важливою частиною цього паттерну оркестрації є тримання викликів Add і Done
Я просто обожнюю цей лінгвістичний прикол: pattern / па**т**ерн, standard / стандар**т**.
https://uk.wikipedia.org/wiki/%D0%9F%D0%B0%D1%82%D0%B5%D1%80%D0%BD

```suggestion
Важливою частиною цього патерну оркестрації є тримання викликів Add і Done
```

2024-06-17 22:07 UTC, abagayev commented on _content/tour/ukr/goroutines.article
> +Ми використовуємо той самий паттерн оркестрування як і раніше, проте в цій програмі кожна
```suggestion
Ми використовуємо той самий патерн оркестрування як і раніше, проте в цій програмі кожна
```

2024-06-17 22:07 UTC, abagayev commented on _content/tour/ukr/goroutines.article
> +- Дізнайтеся більше про конкурентні [[https://github.com/ardanlabs/gotraining/blob/master/topics/go/#concurrent-software-design][паттерни проєктування]].
```suggestion
- Дізнайтеся більше про конкурентні [[https://github.com/ardanlabs/gotraining/blob/master/topics/go/#concurrent-software-design][патерни проєктування]].
```

2024-06-17 22:07 UTC, abagayev commented on _content/tour/ukr/goroutines.article
> +та не невпорядкований.
```suggestion
та невпорядкований.
```

2024-06-17 22:07 UTC, abagayev commented on _content/tour/ukr/goroutines.article
> +*Частина* *A* Cтворіть програму, яка визначає дві анонімних функції. Одну, яка рахуватиме від 100 до 0,
```suggestion
*Частина* *A* Cтворіть програму, яка визначає дві анонімні функції. Одну, яка рахуватиме від 100 до 0,
```

2024-06-17 22:07 UTC, abagayev commented on _content/tour/ukr/goroutines.article
> +до того, як горутині закінчать свою роботу.
```suggestion
до того, як горутини закінчать свою роботу.
```

2024-06-18 05:08 UTC, bulaiocht commented on _content/tour/ukr/goroutines.article
> +*Стани* *потоку:* Потік може бути в одному з трьох станів: *Виконується*, *Запущений*
@abagayev це був мій внесок, бо коли слова без відмінків їх важко сприймати без якогось виділення

2024-06-18 07:24 UTC, bulaiocht commented on _content/tour/ukr/goroutines.article
> +які важко знайти.
@vtopc гонитва озброєння, гонитва даних, мені здається те шо треба

2024-06-18 07:28 UTC, bulaiocht commented on _content/tour/ukr/goroutines.article
> +у стан очікування. Наприклад, отримання даних з різних адрес ресурсів (URL) може
@abagayev можна вкоротити як `URL-адрес`

2024-06-18 08:38 UTC, vtopc commented on _content/tour/ukr/goroutines.article
> +Назва функція написана великими літерами, тому що це також є змінна оточення.
упс

2024-06-20 17:52 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +системиою, проте передає контроль виконання на рівень застосунку.
```suggestion
системою, проте передає контроль виконання на рівень застосунку.
```

2024-06-20 17:52 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +ядер, які доступні програмі. Для кожного потоку, який може бути виконаний у паралелі, середа
Мені здається, немає такого терміну, як ["середа виконання"](https://trends.google.com/trends/explore?date=today%205-y&geo=UA&q=%D1%81%D0%B5%D1%80%D0%B5%D0%B4%D0%B0%20%D0%B2%D0%B8%D0%BA%D0%BE%D0%BD%D0%B0%D0%BD%D0%BD%D1%8F&hl=en-GB).

Можливо, краще змінити на ["середовище виконання"](https://trends.google.com/trends/explore?date=today%205-y&geo=UA&q=%D1%81%D0%B5%D1%80%D0%B5%D0%B4%D0%BE%D0%B2%D0%B8%D1%89%D0%B5%20%D0%B2%D0%B8%D0%BA%D0%BE%D0%BD%D0%B0%D0%BD%D0%BD%D1%8F&hl=en-GB)?

2024-06-20 17:53 UTC, hrvadl commented on _content/tour/ukr/goroutines.article
> +системиою, проте передає контроль виконання на рівень застосунку.
дивно що спелчек цього не помітив. дякую що помітив

2024-06-20 17:53 UTC, hrvadl commented on _content/tour/ukr/goroutines.article
> +ядер, які доступні програмі. Для кожного потоку, який може бути виконаний у паралелі, середа
так, це русизм був. Середовище виконання краще термін

2024-06-20 18:01 UTC, hrvadl commented on _content/tour/ukr/goroutines.article
> +ядер, які доступні програмі. Для кожного потоку, який може бути виконаний у паралелі, середа
@alexandear я поправив, дякую за зауваження, забагато у мене русизмів нажаль

2024-06-20 18:41 UTC, vtopc approved these changes

2024-06-20 18:51 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +на обраних M/P. Так само, як M управляє виконанням інструкцій заліза,
Кома не потрібна:

```suggestion
на обраних M/P. Так само як M управляє виконанням інструкцій заліза, 
```
Пояснення з https://languagetool.org/uk

<img width="1237" alt="image" src="https://github.com/GolangUA/ardanlabs-gotour/assets/3228886/12773f42-20a2-419a-81e8-b88fbe32c1db">

2024-06-20 18:51 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +важливо мати деяке розуміння того, як працює планувальник операційної системи і обмеження,
Пропозиція по стилю:

```suggestion
важливо мати деяке розуміння того, як працює планувальник операційної системи й обмеження,
```

<img width="1204" alt="image" src="https://github.com/GolangUA/ardanlabs-gotour/assets/3228886/056a71d7-104e-46fc-aeb8-94fc0da62f82">

2024-06-20 18:51 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +виконати призначенні йому інструкції, та сидить в черзі виконання. *Очікує* -
Зайва "н":
```suggestion
виконати призначені йому інструкції, та сидить в черзі виконання. *Очікує* -
```

2024-06-20 18:51 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +здатність або контекст виконання для середи виконання програми Go.
```suggestion
здатність або контекст виконання для середовища виконання програми Go.
```

2024-06-20 18:51 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +виконання повного набору інструкцій у будь-якому невизначеному порядку приводить до того
```suggestion
виконання повного набору інструкцій у будь-якому невизначеному порядку призводить до того
```

[Призводити, спричинювати, наводити, надавати, зводити і приводити](https://onlinecorrector.com.ua/uk/%D0%BF%D1%80%D0%B8%D0%B7%D0%B2%D0%BE%D0%B4%D0%B8%D1%82%D0%B8-%D1%81%D0%BF%D1%80%D0%B8%D1%87%D0%B8%D0%BD%D1%8E%D0%B2%D0%B0%D1%82%D0%B8-%D0%BD%D0%B0%D0%B2%D0%BE%D0%B4%D0%B8%D1%82%D0%B8)

2024-06-20 18:51 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +то це приводить до гонитви даних (data races). Гонитва даних є причиною багатьох багів з пошкодженням даних,
```suggestion
то це спричинює гонитву даних (data races). Гонитва даних є причиною багатьох багів з пошкодженням даних,
```

[Призводити, спричинювати, наводити, надавати, зводити і приводити](https://onlinecorrector.com.ua/uk/%D0%BF%D1%80%D0%B8%D0%B7%D0%B2%D0%BE%D0%B4%D0%B8%D1%82%D0%B8-%D1%81%D0%BF%D1%80%D0%B8%D1%87%D0%B8%D0%BD%D1%8E%D0%B2%D0%B0%D1%82%D0%B8-%D0%BD%D0%B0%D0%B2%D0%BE%D0%B4%D0%B8%D1%82%D0%B8)

2024-06-20 18:51 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +Ви повинні впевнитися в тому, що це число збігається з числом потоків операційної системи,
```suggestion
Ви маєте впевнитися в тому, що це число збігається з числом потоків операційної системи, 
```

[Мати, мусити, винен і повинен](https://onlinecorrector.com.ua/uk/%D0%BC%D0%B0%D1%82%D0%B8-%D0%BC%D1%83%D1%81%D0%B8%D1%82%D0%B8-%D0%B2%D0%B8%D0%BD%D0%B5%D0%BD)

2024-06-20 18:51 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +які ми створюємо. Коли ви знаєте, скільки горутин буде створено завчасно, ви повинні
```suggestion
які ми створюємо. Коли ви знаєте, скільки горутин буде створено завчасно, ви маєте
```

[Мати, мусити, винен і повинен](https://onlinecorrector.com.ua/uk/%D0%BC%D0%B0%D1%82%D0%B8-%D0%BC%D1%83%D1%81%D0%B8%D1%82%D0%B8-%D0%B2%D0%B8%D0%BD%D0%B5%D0%BD)

2024-06-20 18:51 UTC, alexandear commented on _content/tour/ukr/goroutines.article
> +- Ми повинні завжди мати на увазі кількість активних горутин, та завершувати роботу чисто.
```suggestion
- Ми маємо завжди мати на увазі кількість активних горутин та завершувати роботу чисто.
```


[Мати, мусити, винен і повинен](https://onlinecorrector.com.ua/uk/%D0%BC%D0%B0%D1%82%D0%B8-%D0%BC%D1%83%D1%81%D0%B8%D1%82%D0%B8-%D0%B2%D0%B8%D0%BD%D0%B5%D0%BD)

2024-06-25 07:45 UTC, bulaiocht approved these changes

2024-06-25 10:09 UTC, alexandear approved these changes
LGTM

2024-06-25 21:36 UTC, abagayev approved these changes

2024-06-26 06:03 UTC, merged